In [10]:
# imports
print('---Loading Imports')
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import os
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
print('---Success')

---Loading Imports
---Success


In [11]:
# import the uci dataset
print('---Importing the uci dataset')
uci_train = []
training_data_all=[]
x_train_data = []
y_train_data = []
uci_dir = 'uci_dataset'
training_data_file = 'shuttle.trn'

print('---Success')
print('----------------------------')

# load the training data
print('---Loading the training data')
with open('./'.join([os.getcwd(), uci_dir, training_data_file])) as f:
    
    for line in f:
        uci_train.append(line) # for checking if split of data is correct
        split = line.strip().split(' ')
        training_data_val =[ int(x) for x in split]
        x_values = [ float(x) for x in split[:-1]]
        y_values = int(split[-1])
        
        training_data_all.append(training_data_val)
        x_train_data.append(x_values)
        y_train_data.append([y_values])
        
print('---Success')
print('----------------------------')
        
print('Loading training data lengths')
print('x_train_data length: ', len(x_train_data))
print('y_train_data length: ', len(y_train_data))
print('----------------------------')


# load the training data
uci_test = []
x_test_data = []
y_test_data = []
test_data_file = 'shuttle.tst'

with open('/'.join([os.getcwd(), uci_dir, test_data_file])) as f:
    
    for line in f:
        uci_test.append(line) # for checking if split of data is correct
        split = line.strip().split(' ')
        x_values = [ float(x) for x in split[:-1]]
        y_values = int(split[-1])
        
        x_test_data.append(x_values)
        y_test_data.append([y_values])

print('Loading test data lengths')
print('x_test_data length: ', len(x_test_data))

print('y_test_data length: ', len(y_test_data))
print('----------------------------')

print('Total data length is: %d' % (len(x_train_data) + len(x_test_data)))


---Importing the uci dataset
---Success
----------------------------
---Loading the training data
---Success
----------------------------
Loading training data lengths
x_train_data length:  43500
y_train_data length:  43500
----------------------------
Loading test data lengths
x_test_data length:  14500
y_test_data length:  14500
----------------------------
Total data length is: 58000


In [12]:
print('---randomized training data by reducing class 1')
# reorganization training data
count=0
x_reorganization_data=[]
y_reorganization_data=[]
for x,y in zip(x_train_data,y_train_data):
    if y[0]==1:
        count+=1
        if (count%5)==0: 
            x_reorganization_data.append(x)
            y_reorganization_data.append(y)
       #     print('append 1')
       # print('y==1',count,' - ',y,'not append 1')
    else:
        x_reorganization_data.append(x)
        y_reorganization_data.append(y)
       # print('y!=1',count,' - ',y,'append others')
print('============ reorganization dataset======================')   
print('x_reorganization_data length: ',len(x_reorganization_data))
print('y_reorganization_data length: ',len(y_reorganization_data))
#print(x_reorganization_data[0:10])
#print(y_reorganization_data[0:10])

print('============ training dataset======================')
# count the number of data for each classes - training dataset
total_num_data = len(x_train_data)
train_bins = [[] for _ in range(7)]
for x, y in zip(x_train_data, y_train_data):
    train_bins[y[0] - 1].append(x)
    
print('Training dataset:')
for idx, category in enumerate(train_bins):
    print('class %d: count: %d ratio: %.2f%%' % (idx + 1, len(category), (len(category)/float(total_num_data)) * 100) )
    
#print('====data train_bins:====')
#print(train_bins)

print('============ reorganization dataset======================')
total_num_data = len(x_reorganization_data)
train_bins = [[] for _ in range(7)]
for x, y in zip(x_reorganization_data, y_reorganization_data):
    train_bins[y[0] - 1].append(x)
    
print('reorganization dataset:')
for idx, category in enumerate(train_bins):
    print('class %d: count: %d ratio: %.2f%%' % (idx + 1, len(category), (len(category)/float(total_num_data)) * 100) )


print('===============count the number of data for each classes - test dataset=====================================')
# count the number of data for each classes - test dataset
total_num_data = len(x_test_data)
test_bins = [[] for _ in range(7)]
for x, y in zip(x_test_data, y_test_data):
    test_bins[y[0] - 1].append(x)
    
print('Test dataset:')
for idx, category in enumerate(test_bins):
    print('class %d: count: %d ratio: %.2f%%' % (idx + 1, len(category), (len(category)/float(total_num_data)) * 100) )

---randomized training data by reducing class 1
============ reorganization dataset======================
x_reorganization_data length:  16213
y_reorganization_data length:  16213
============ training dataset======================
Training dataset:
class 1: count: 34108 ratio: 78.41%
class 2: count: 37 ratio: 0.09%
class 3: count: 132 ratio: 0.30%
class 4: count: 6748 ratio: 15.51%
class 5: count: 2458 ratio: 5.65%
class 6: count: 6 ratio: 0.01%
class 7: count: 11 ratio: 0.03%
============ reorganization dataset======================
reorganization dataset:
class 1: count: 6821 ratio: 42.07%
class 2: count: 37 ratio: 0.23%
class 3: count: 132 ratio: 0.81%
class 4: count: 6748 ratio: 41.62%
class 5: count: 2458 ratio: 15.16%
class 6: count: 6 ratio: 0.04%
class 7: count: 11 ratio: 0.07%
===============count the number of data for each classes - test dataset=====================================
Test dataset:
class 1: count: 11478 ratio: 79.16%
class 2: count: 13 ratio: 0.09%
class 3: co

In [ ]:
print('Using an svm with rbf kernel function:')
# Use an svm with rbf kernel function
svm = SVC(C=20, kernel='rbf', gamma=20)
svm.fit(x_train_data, y_train_data)
#print(training_data_all)
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

#testing
print(svm.predict(x_train_data))
print('the SVM Accuracy::',svm.score(x_train_data, y_train_data))


from sklearn import preprocessing
print(preprocessing.scale(x_reorganization_data))




In [14]:
# TODO: Do cross validation
# Possible approaches
# 1. k-fold cross validation
# 2. Try different algorithm
# 3. Under/Oversampling method
# 4. Penalized Models (penalized SVM)
# 5. Look into Anomaly Detection

# Cross Validation techniques (Non-exhaustive methods)
# 1. Holdout Method
# 2. k-fold cross validation
# 3. Stratified k-fold cross validation
#    - each fold contains approximately the same 
#    percentage of samples of each target class
#    in the case of prediction problems, the mean response value is approximately equal in all folds
# (Exhaustive methods)
# 4. Leave-P-Out Cross Validation


# K- CV
scores = cross_val_score(svm, preprocessing.scale(x_reorganization_data), np.ravel(y_reorganization_data,order='C'), cv=6, scoring='accuracy')

#
print(scores)
# original Imbalanced data
# [0.78377757 0.78395771 0.78413793 0.78429343 0.78429343]

[0.99260355 0.99408065 0.99223085 0.98927118 0.99296557 0.99555391]


In [15]:
# K- CV
scores = cross_val_score(svm, preprocessing.scale(x_reorganization_data), np.ravel(y_reorganization_data,order='C'), cv=5, scoring='accuracy')

#
print(scores)
# original Imbalanced data
# [0.78377757 0.78395771 0.78413793 0.78429343 0.78429343]

# decrease class1 in 1/5
# [0.98306129 0.98335388 0.97902529 0.98117284 0.98364198]


print(scores.mean())
# original Imbalanced data
# 0.7840920168940516

# decrease class1 in 1/5
# 0.9820510558559367

[0.99137666 0.99260173 0.9910549  0.99351852 0.99475309]
0.9926609781912695


In [16]:
# training
svm.fit(preprocessing.scale(x_reorganization_data), np.ravel(y_reorganization_data,order='C'))

#testing
print(svm.predict(x_test_data))
print('the SVM Accuracy::',svm.score(x_test_data, y_test_data))

[1 1 1 ... 1 1 1]
the SVM Accuracy:: 0.7915862068965517
